91488c91-817c-4ca1-b95e-55aa037b9313
error: Traceback (most recent call last):
  File "calc_refine_structure.py", line 349, in <module>
    main(*sys.argv[1:])    
  File "calc_refine_structure.py", line 36, in main
    potential = lmp.Potential(input_dict['potential'], input_dict['potential_dir'])        
  File "c:\users\lmh1\documents\python-packages\atomman\atomman\lammps\Potential.py", line 17, in __init__
    self.load(model, pot_dir)
  File "c:\users\lmh1\documents\python-packages\atomman\atomman\lammps\Potential.py", line 28, in load
    self.__dm = DataModelDict(model).find('LAMMPS-potential')        
  File "c:\users\lmh1\documents\python-packages\datamodeldict\DataModelDict.py", line 46, in __init__
    self.update(*args, **kwargs)
  File "C:\Anaconda\lib\_abcoll.py", line 571, in update
    for key, value in other:
TypeError: 'Potential' object is not iterable


d2399327-3dfc-47ec-937b-b1b8dfe06cc7
error: Traceback (most recent call last):
  File "calc_refine_structure.py", line 349, in <module>
    main(*sys.argv[1:])    
  File "calc_refine_structure.py", line 36, in main
    potential = lmp.Potential(input_dict['potential'], input_dict['potential_dir'])        
  File "c:\users\lmh1\documents\python-packages\atomman\atomman\lammps\Potential.py", line 17, in __init__
    self.load(model, pot_dir)
  File "c:\users\lmh1\documents\python-packages\atomman\atomman\lammps\Potential.py", line 28, in load
    self.__dm = DataModelDict(model).find('LAMMPS-potential')        
  File "c:\users\lmh1\documents\python-packages\datamodeldict\DataModelDict.py", line 46, in __init__
    self.update(*args, **kwargs)
  File "C:\Anaconda\lib\_abcoll.py", line 571, in update
    for key, value in other:
TypeError: 'Potential' object is not iterable


